development:
  adapter:  postgresql
  encoding: utf8
  host:  127.0.0.1
  pool: 5
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  database:  note_db
  timeout:   5000  